apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
  labels:
    app: mi-aplicacion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: mi-contenedor
        image: carloandrepb/docker01-andres-pillajo:latest
        ports:
        - containerPort: 5000
---